add clear user param to disconnect
GetStream/stream-chat-dart pull request #76
Opened 2020-12-15 22:37 UTC by imtoori

If true dispose the client state and instantiate a new one

2020-12-15 22:42 UTC, Nash0x7E2 requested changes
Left some comments @imtoori. What do you think?

2020-12-15 22:42 UTC, Nash0x7E2 commented on lib/src/client.dart
>    /// Closes the websocket connection and resets the client
I think we should update the documentation for this method as well.

2020-12-15 22:42 UTC, Nash0x7E2 commented on lib/src/client.dart
> +    if (clearUser == true) {
What about a log here? Might be useful for debugging purposes. At the very least, we can log the options the function was called with.

2020-12-16 09:05 UTC, vishalnarkhede commented
@mahboubii we should do the same later for js client

```js
client.disconnect({ clearUser: false }):
client.connect()
```

is much better than

```js
client.wsConnection.disconnect() 
client.setupConnection()

// (this is what we recommend to customers right now)
```

for disconnecting and reconnecting experience, which is mostly used for foregrounding/background the application.

What do you think?

2020-12-16 09:37 UTC, mahboubii commented
> @mahboubii we should do the same later for js client
> 
> ```js
> client.disconnect({ clearUser: false }):
> client.connect()
> ```
> 
> is much better than
> 
> ```js
> client.wsConnection.disconnect() 
> client.setupConnection()
> 
> // (this is what we recommend to customers right now)
> ```
> 
> for disconnecting and reconnecting experience, which is mostly used for foregrounding/background the application.
> 
> What do you think?

yea sounds good to me, we need to do some work around all the WS stuff

2020-12-16 17:15 UTC, Nash0x7E2 approved these changes
LGTM

2020-12-16 17:15 UTC, merged